---
- hosts: ec2-35-176-139-111.eu-west-2.compute.amazonaws.com
  tasks:
    - name: Installs nginx web server
      apt: pkg=nginx state=installed update_cache=true
      notify:
        - start nginx

  handlers:
    - name: start nginx
      service: name=nginx state=started

