---
- hosts: base
  user: ubuntu
  sudo: True
  tasks:
    - name: Installs nginx web server
      apt: pkg=nginx state=installed update_cache=true
      notify:
        - start nginx

    - name: This command will change the working directory to somedir/ and will only run when somedir/somelog.txt doesn't exist.
      shell: echo ${env} >> /tmp/somelog.txt
      args:
        chdir: /tmp/
        creates: /tmp/somelog.txt

  handlers:
    - name: start nginx
      service: name=nginx state=started

